// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPr6r432OhaINwxV_ZjvdaokWGh8zNmAs',
    appId: '1:872433738843:web:17c4388db9cbadf4974b7e',
    messagingSenderId: '872433738843',
    projectId: 'employee-management-88315',
    authDomain: 'employee-management-88315.firebaseapp.com',
    storageBucket: 'employee-management-88315.appspot.com',
    measurementId: 'G-6DSZ3GW6F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmG-rntrsIje8qEPIMvgpWYLL28kkcNgQ',
    appId: '1:872433738843:android:7580baf92ea994fa974b7e',
    messagingSenderId: '872433738843',
    projectId: 'employee-management-88315',
    storageBucket: 'employee-management-88315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Ju8BryppNwUjBb7-lHQe29X6QFs1NCE',
    appId: '1:872433738843:ios:2be457be9be688af974b7e',
    messagingSenderId: '872433738843',
    projectId: 'employee-management-88315',
    storageBucket: 'employee-management-88315.appspot.com',
    iosClientId: '872433738843-iuorilastj6jl9m3el68ehsb8p4r3j51.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Ju8BryppNwUjBb7-lHQe29X6QFs1NCE',
    appId: '1:872433738843:ios:2be457be9be688af974b7e',
    messagingSenderId: '872433738843',
    projectId: 'employee-management-88315',
    storageBucket: 'employee-management-88315.appspot.com',
    iosClientId: '872433738843-iuorilastj6jl9m3el68ehsb8p4r3j51.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPr6r432OhaINwxV_ZjvdaokWGh8zNmAs',
    appId: '1:872433738843:web:c34c752465063efb974b7e',
    messagingSenderId: '872433738843',
    projectId: 'employee-management-88315',
    authDomain: 'employee-management-88315.firebaseapp.com',
    storageBucket: 'employee-management-88315.appspot.com',
    measurementId: 'G-Z8P05H3PYG',
  );
}
